### PR TITLE
[SENT 27/11/17] Digest

### PR DESCRIPTION
**Pull request by nvgrw**
Review pls

[predigest1.pdf](https://github.com/icdocsoc/emails/files/1507801/predigest1.pdf)

### CODE REVIEW

**Comment by ThomasBower** [comment]
Looks fine to me.

**Comment by nvgrw** [comment]
Should I put the bar night @ThomasBower

**Comment by ThomasBower** [comment]
It's quite far in advance, and you'll include it in the next two digests anyway, so it's up to you.

**Comment by ThomasBower** [comment]
I also remembered we should include the Christmas Party - can you sync with Diana for the content?

**Comment by nvgrw** [comment]
I'll not include it yet then, feels a bit early still. Christmas party event is still a draft on fb?

**Pull request merged**
